### ISSUE TITLE
Investigate screen recording

### ISSUE THREAD

**Issue by Armaldio** [ElectronForConstruct/cli#15]

**Comment by MikalDev** [comment]
Do you mean integrated screen recording via a module? It also looks like a new release of C3 has screen recording, but needs a later version of chromium.

**Comment by Armaldio** [comment]
No, I remember someone told me he can't screen record using OBS

If you know a way, add it to the docs

**Comment by MikalDev** [comment]
I was able to record with OBS. Didn’t do anything special to do it, just ran OBS and added the electron app window as a source.
