### ISSUE TITLE
MacOS steam_appid.txt copy incorrect?

### ISSUE THREAD

**Issue by MikalDev** [ElectronForConstruct/cli#19]
4/8 - .DS_Store (Configure greenworks) ...
cp: copyFileSync: could not write to dest file (code=ENOTDIR):/Users/Mikal/Projects/Construct3Projects/DungeonSdS/dist/.DS_Store/steam_appid.txt

efc 2.3.6
MacOS 10.14.3

**Comment by Armaldio** [comment]
Can't reproduce on windows, can you share more infos ?

**Comment by Armaldio** [comment]
see #22
